CSOURCES=mipssim.c mips_load.c
CPPSOURCES=
EXECUTABLE=mipssim

OBJECTS=$(CPPSOURCES:.cpp=.o) $(CSOURCES:.c=.o) $(ASMSOURCES:.asm=.o)
# The default linker is gcc. Use ld if you have other requirements 

#for C
CC=gcc 
CFLAGS=-c -Wall -g -O3

#for CPP
CXX=g++ 
CXXFLAGS=-c -Wall -g

#linker
LD=$(CC)
LDFLAGS=

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS) 
	$(LD) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CXX) $(CFLAGS) $< -o $@

.c.o:
	$(CC) $(CFLAGS) $< -o $@

clean :
	rm -rf *.o $(EXECUTABLE)

#Dependency generated by gcc -MM
mips_load.o: mips_load.c mipssim.h

mipssim.o: mipssim.c mipssim.h
